version: '3'
services:
    weatherforecastapp:
        image: 'time2pretend/weatherforecastapp-sql:latest'
        ports:
            - '8000:80'
        depends_on:
            - weatherforecastdb
    weatherforecastdb:
        image: 'time2pretend/weatherforecastdb-sql:latest'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Sample123
        ports:
            - '1433:1433'
