version: "3"
services:
    weatherforecastapp:
        build:
            context: ./src
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - weatherforecastdb
    weatherforecastdb:
        build:
            context: ./sql
            dockerfile: Dockerfile
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Sample123
        ports:
            - "1433:1433"
